image: node:latest

cache:
  paths:
    - node_modules/
    - $HOME/.yarn-cache

test:
  script:
    - npm install
    - npm test

generate-document:
  script:
    - npm install
    - npm run generate-document
