image: node:latest

cache:
  paths:
    - node_modules/
    - $HOME/.yarn-cache

test:
  script:
    - npm install
    - npm test

pages:
  script:
    - npm install
    - npm run generate-document
  artifacts:
    paths:
      - public
  only:
      - master
