image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test
  only:
      - develop
      - master

pages:
  stage: deploy
  script:
    - npm install
    - npm run generate-document
  artifacts:
    paths:
      - public
  only:
      - master
