import { TNWayOption,
         TSpreadOption,
         TWhipOption,
         concat,
         fire,
         nWay,
         paraRepeat,
         parallel,
         parallelRepeat,
         repeat,
         sequential,
         spread,
         wait,
         whip} from './gun';
import { addAngle,
         addNWayAngle,
         addSize,
         addSpeed,
         addParameter,
         addVector,
         mltAngle,
         mltLaterAddingParameter,
         mltLaterAngle,
         mltLaterSize,
         mltLaterSpeed,
         mltParameter,
         mltSize,
         mltSpeed,
         resetAngle,
         resetParameter,
         resetSize,
         resetSpeed,
         setMuzzle,
         setText,
         setVector} from './gunModifier';
import * as lazyEvaluative from './lazyEvaluative';

export {
    TNWayOption,
    TSpreadOption,
    TWhipOption,
    concat,
    fire,
    nWay,
    paraRepeat,
    parallel,
    parallelRepeat,
    repeat,
    sequential,
    spread,
    wait,
    whip,
    addAngle,
    addNWayAngle,
    addSize,
    addSpeed,
    addParameter,
    addVector,
    mltAngle,
    mltLaterAddingParameter,
    mltLaterAngle,
    mltLaterSize,
    mltLaterSpeed,
    mltParameter,
    mltSize,
    mltSpeed,
    resetAngle,
    resetParameter,
    resetSize,
    resetSpeed,
    setMuzzle,
    setText,
    setVector,
    lazyEvaluative,
};
